version: '3.8'

services:
  jekyll-site:
    image: vitorholanda/website:latest
    container_name: vitor_website2
    restart: always
    ports:
      - "4000:4000"
    environment:
      - PAGES_REPO_NWO=VitorHolandaI/VitorHolandaI
    command: jekyll serve --host 0.0.0.0

